### ISSUE TITLE
Remove usage of `LogStash::SHUTDOWN`

### ISSUE THREAD

**Issue by andsel** [logstash-plugins/logstash-output-nagios_nsca#18]
With the removal of Ruby Execution Engine https://github.com/elastic/logstash/pull/12517 the `LogStash::SHUTDOWN` was removed.
This plugin [starts failing](https://app.travis-ci.com/github/logstash-plugins/logstash-output-nagios_nsca/jobs/538358481#L480) on `8.0`.

**Build scan**:
https://app.travis-ci.com/github/logstash-plugins/logstash-output-nagios_nsca/jobs/538358481#L480

**Repro line**:
NA

**Reproduces locally?**:
Yes

**Applicable branches**:
`master`

**Failure history**:

**Failure excerpt**:
```
logstash_1_d54db825a42b | Failures:
logstash_1_d54db825a42b | 
logstash_1_d54db825a42b |   1) LogStash::Outputs::NagiosNsca send send the event to nagios
logstash_1_d54db825a42b |      Failure/Error: return if event == LogStash::SHUTDOWN
logstash_1_d54db825a42b |      
logstash_1_d54db825a42b |      NameError:
logstash_1_d54db825a42b |        uninitialized constant LogStash::SHUTDOWN
logstash_1_d54db825a42b |        Did you mean?  LogStash::ShutdownSignal
logstash_1_d54db825a42b |      # ./lib/logstash/outputs/nagios_nsca.rb:69:in `receive'
logstash_1_d54db825a42b |      # ./spec/outputs/nagios_nsca_spec.rb:26:in `block in <main>'
```

**Comment by Hellnino18** [comment]
Hi there !

What about this issue ? Do you plan to fix this problem with any ETA ? I can't use nagios_nsca output anymore since I upgraded to Elastic 8.4.3.

Thanks for your help (Elastic support told me to contact the dev platform about this issue).
